apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mern-frontend
  # TODO: set namespace (match Deployment)
  labels:
    app.kubernetes.io/name: mern-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: mern-frontend
    app.kubernetes.io/managed-by: kustomize
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mern-frontend
      app.kubernetes.io/component: frontend
