apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  # TODO: set namespace
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: mern-stack
    app.kubernetes.io/managed-by: k8s-manifests
type: Opaque
data:
  MONGO_URI: "BASE64_TODO_SET_MONGO_URI"
