apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  # TODO: set namespace
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: mern-stack
    app.kubernetes.io/managed-by: k8s-manifests
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # TODO: set storageClassName explicitly to match your storage policy
  # storageClassName: <TODO-set-storageclass>
