apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  # TODO: set namespace
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: mern-stack
    app.kubernetes.io/managed-by: k8s-manifests
spec:
  serviceName: mongo
  replicas: 1 # TODO: increase if HA is required (and switch to per-pod volumes)
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/component: database
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: mern-stack
        app.kubernetes.io/managed-by: k8s-manifests
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: 999
      containers:
        - name: mongo
          image: mongo:7.0.14
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_DATABASE
          readinessProbe:
            tcpSocket:
              port: mongo
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: mongo
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
            # TODO: tune resources for production based on workload
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false # TODO: set true only if verified compatible
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      # TODO: add serviceAccountName if IRSA/RBAC is required
  volumeClaimTemplates: []
  # Using a pre-created PVC (see pvc.yaml). If switching to HA, use volumeClaimTemplates.
